/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/Accordion.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Counter: typeof import('./src/components/Counter.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    ProductCard: typeof import('./src/components/Products/ProductCard.vue')['default']
    ProductList: typeof import('./src/components/Products/ProductList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
  }
}
